# Dockerfile.dev
FROM mcr.microsoft.com/dotnet/sdk:9.0-preview
WORKDIR /app

COPY . ./
RUN dotnet restore

EXPOSE 5120
ENV ASPNETCORE_ENVIRONMENT=Development

CMD ["dotnet", "watch", "run", "--urls=http://0.0.0.0:5120"]