services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages # cache nuget
    ports:
      - "8080:5120"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ProductServiceDb;Username=postgres;Password=password123;
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: productservice-postgres-dev
    environment:
      - POSTGRES_DB=ProductServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - "5433:5432" # Different port for dev to avoid conflicts
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_dev_data:

networks:
  app-network:
    driver: bridge
