version: "3.0"
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:5121"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ProductServiceDb;Username=postgres;Password=password123;
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: productservice-postgres
    environment:
      - POSTGRES_DB=ProductServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
